// Mocks generated by Mockito 5.4.4 from annotations
// in firstapp/test/emotion_recorder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:firstapp/database/database.dart' as _i2;
import 'package:firstapp/entity/RecordingPoints.dart' as _i5;
import 'package:firstapp/recording_provider_info.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecordingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingProvider extends _i1.Mock implements _i3.RecordingProvider {
  MockRecordingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.AppDatabase);

  @override
  set lastRecordingTime(DateTime? _lastRecordingTime) => super.noSuchMethod(
        Invocation.setter(
          #lastRecordingTime,
          _lastRecordingTime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get recordingPoints => (super.noSuchMethod(
        Invocation.getter(#recordingPoints),
        returnValue: 0,
      ) as int);

  @override
  set recordingPoints(int? _recordingPoints) => super.noSuchMethod(
        Invocation.setter(
          #recordingPoints,
          _recordingPoints,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastEventType(String? _lastEventType) => super.noSuchMethod(
        Invocation.setter(
          #lastEventType,
          _lastEventType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> addEvents(_i5.Status? status) => (super.noSuchMethod(
        Invocation.method(
          #addEvents,
          [status],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void recordEvent(
    String? eventType,
    DateTime? lastTime,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #recordEvent,
          [
            eventType,
            lastTime,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int calculatePoints(Duration? timeSinceLastRecording) => (super.noSuchMethod(
        Invocation.method(
          #calculatePoints,
          [timeSinceLastRecording],
        ),
        returnValue: 0,
      ) as int);

  @override
  int calculateDedicationLevel() => (super.noSuchMethod(
        Invocation.method(
          #calculateDedicationLevel,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
